---
run:
  timeout: 1m

linters:
  enable-all: true
  disable:
    - cyclop
    - exhaustivestruct
    - exhaustruct
    - gochecknoglobals
    - godox
    - paralleltest
    - tagliatelle
    - testpackage
    - varnamelen
    - wrapcheck
  fast: false

# Settings for specific linters
linters-settings:
  funlen:
    lines: 200
    statements: 45
  gocognit:
    min-complexity: 35

issues:
  exclude:
    - do not define dynamic errors

  exclude-rules:
    - path: cmd/
      linters:
        - gochecknoinits
        - gomnd
        - forbidigo

    - path: internal/http/
      linters:
        - unparam
        - nlreturn

    - path: _test\.go
      linters:
        - scopelint
        - wsl
        - nlreturn
        - funlen
        - dupl
        - ifshort
        - forcetypeassert
        - lll
        - goerr113

    - path: doc.go
      linters:
        - lll

    - linters:
        - lll
      source: "json:"

    - linters:
        - gocritic
        - godot
      source: "//////"
